doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                MachineState:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/mapping'
                    prefix: 'App\Domain\VendingMachine\Model'
                    alias: MachineState
