version: '3.7'
services:
  php:
    build: .
    links:
      - mongo
    volumes:
      - .:/application

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/application

  mongo:
      image: mongo:4
      restart: always
      volumes:
          - db-volume:/data/db
      environment:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    links:
        - mongo
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
        ME_CONFIG_MONGODB_ADMINPASSWORD: secret

volumes:
  db-volume:
